# region Developer Information
# ----------------------------------------
#    Author: Andrew Laychak
#    Email: ALaychak@harriscomputer.com
#
#    Created At: 01-06-2022 08:59:29 AM
#    Last Modified: 01-06-2022 08:59:56 AM
#    Last Updated By: Andrew Laychak
#
#    Description: The labels that will be used for the labeler workflow
#
#    References:
#      - https://github.com/actions/labeler
# ----------------------------------------
# #endregion

api:
  - 'packages/manager/**/*'
website:
  - 'documentation/website/**/*'
