#   Author: Andrew Laychak
#   Email: ALaychak@HarrisComputer.com
#
#   Created At: 10-18-2021 10:30:14 AM
#   Last Modified: 10-20-2021 09:34:38 AM
#   Last Updated By: Andrew Laychak
#
#   Description: Validates a pull request to verify it conforms to naming conventions
#
#   References:
#     - https://github.com/amannn/action-semantic-pull-request

name: 'Validate PR'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.2
        with:
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
